version: '1.0'

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pgkey
      POSTGRES_DB: business_db
    ports:
      - 5432:5432
    
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: steve.didgi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgkey
    ports:
      - 5050:80